# Generated by Django 2.0.1 on 2018-02-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0008_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='test/%Y/%m/%d'),
        ),
    ]
