# Generated by Django 2.0.3 on 2018-03-22 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0009_auto_20180208_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
