# Generated by Django 2.0.7 on 2018-07-17 02:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0014_auto_20180712_1531'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.PositiveIntegerField(default=None, null=True)),
                ('parent_author', models.CharField(default=None, max_length=100, null=True)),
                ('group', models.PositiveIntegerField(default=None)),
                ('seq_in_group', models.PositiveIntegerField(default=0)),
                ('depth', models.PositiveIntegerField(default=1)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qna_comment_author', to='accounts.UserProfile')),
            ],
            options={
                'ordering': ['group', 'seq_in_group'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tips/images/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qna_iamge_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Qna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('video', models.FileField(blank=True, upload_to='tips/video/%Y/%m/%d')),
                ('slug', models.SlugField(allow_unicode=True, editable=False, max_length=100)),
                ('text', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('views', models.PositiveIntegerField(default=0)),
                ('push_update', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
                ('likes', models.ManyToManyField(blank=True, editable=False, related_name='qna_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='image',
            name='qna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='qna.Qna'),
        ),
        migrations.AddField(
            model_name='comment',
            name='qna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qna.Qna'),
        ),
    ]
