# Generated by Django 2.0.7 on 2018-07-17 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qna',
            name='push_update',
        ),
    ]
