# Generated by Django 2.0.7 on 2018-07-18 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_auto_20180717_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qna',
            old_name='rating',
            new_name='qnarating',
        ),
        migrations.RenameField(
            model_name='qna',
            old_name='text',
            new_name='qnatext',
        ),
        migrations.RenameField(
            model_name='qna',
            old_name='title',
            new_name='qnatitle',
        ),
        migrations.RenameField(
            model_name='qna',
            old_name='video',
            new_name='qnavideo',
        ),
    ]
