# Generated by Django 2.0.7 on 2018-07-18 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0004_auto_20180718_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qna',
            old_name='qnatitle',
            new_name='q_title',
        ),
        migrations.RenameField(
            model_name='qna',
            old_name='qnarating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='qna',
            old_name='qnatext',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='qna',
            old_name='qnavideo',
            new_name='video',
        ),
    ]
