# Generated by Django 2.0.7 on 2018-07-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0005_auto_20180718_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to='qna/images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='qna',
            name='video',
            field=models.FileField(blank=True, upload_to='qna/video/%Y/%m/%d'),
        ),
    ]
