# Generated by Django 2.0.7 on 2018-07-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0006_auto_20180719_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qna',
            name='q_title',
            field=models.CharField(max_length=100),
        ),
    ]
