# Generated by Django 2.0.3 on 2018-04-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='video',
            field=models.FileField(blank=True, upload_to='tips/video/%Y/%m/%d'),
        ),
    ]
