# Generated by Django 2.0.3 on 2018-03-21 06:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subway',
            name='image_files',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='subway',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
