# Generated by Django 2.0.3 on 2018-04-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_auto_20180403_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to='tips/images/%Y/%m/%d'),
        ),
    ]
