# Generated by Django 2.0.3 on 2018-03-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_auto_20180323_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='text',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='video',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
