# Generated by Django 2.0.3 on 2018-03-21 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_auto_20180321_1507'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subway',
        ),
    ]
