# Generated by Django 2.0.3 on 2018-03-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0003_auto_20180323_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='category',
            name='text',
            field=models.TextField(),
        ),
    ]
