# Generated by Django 2.0.3 on 2018-04-10 03:07

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0003_auto_20180410_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listicle',
            name='articles',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='category', chained_model_field='listicle', horizontal=True, to='tips.Article'),
        ),
    ]
