# Generated by Django 2.0.3 on 2018-03-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0004_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=20, primary_key=True, verbose_name='Title'),
        ),
    ]
