# Generated by Django 2.0.3 on 2018-03-28 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0005_auto_20180327_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='likes',
        ),
    ]
