# Generated by Django 2.0.3 on 2018-04-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0006_auto_20180410_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles_listicle',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='articles_listicle',
            name='category',
        ),
        migrations.AlterField(
            model_name='listicle',
            name='articles',
            field=models.ManyToManyField(related_name='listicle_articles', to='tips.Article'),
        ),
        migrations.DeleteModel(
            name='articles_listicle',
        ),
    ]
