# Generated by Django 2.0.3 on 2018-04-04 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0007_auto_20180404_1033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id']},
        ),
    ]
