# Generated by Django 2.0.3 on 2018-04-13 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0008_auto_20180413_0842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
