# Generated by Django 2.0.3 on 2018-04-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0009_listicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='listicle',
            name='file',
            field=models.FileField(default=11, upload_to='tips/listicle/images/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listicle',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
