# Generated by Django 2.0.3 on 2018-04-13 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0009_auto_20180413_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
