# Generated by Django 2.0.3 on 2018-03-22 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0009_auto_20180322_1340'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='Category',
        ),
    ]
