# Generated by Django 2.0.3 on 2018-04-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0010_auto_20180405_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listicle',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Title'),
        ),
    ]
