# Generated by Django 2.0.3 on 2018-03-22 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0010_auto_20180322_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='gallery',
            new_name='category',
        ),
    ]
