# Generated by Django 2.0.3 on 2018-04-05 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0011_auto_20180405_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listicle',
            old_name='file',
            new_name='Image',
        ),
        migrations.AddField(
            model_name='listicle',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tips.Category'),
        ),
    ]
