# Generated by Django 2.0.3 on 2018-04-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0012_auto_20180405_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listicle',
            name='Image',
            field=models.FileField(blank=True, upload_to='tips/listicle/images/%Y/%m/%d'),
        ),
    ]
