# Generated by Django 2.0.3 on 2018-04-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0012_auto_20180413_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['parent']},
        ),
        migrations.AddField(
            model_name='comment',
            name='group',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
