# Generated by Django 2.0.3 on 2018-03-22 04:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0013_auto_20180322_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='section',
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, primary_key=True, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
