# Generated by Django 2.0.3 on 2018-04-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0013_auto_20180413_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['group', 'id']},
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_writer',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
