# Generated by Django 2.0.3 on 2018-04-05 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0013_auto_20180405_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listicle',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
