# Generated by Django 2.0.3 on 2018-04-09 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0014_auto_20180405_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listicle',
            old_name='Image',
            new_name='image',
        ),
    ]
