# Generated by Django 2.0.3 on 2018-03-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0014_auto_20180322_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Title'),
        ),
    ]
