# Generated by Django 2.0.3 on 2018-04-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0014_auto_20180413_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_writer',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
