# Generated by Django 2.0.3 on 2018-03-22 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0015_auto_20180322_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
    ]
