# Generated by Django 2.0.3 on 2018-03-22 05:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0016_remove_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
