# Generated by Django 2.0.3 on 2018-04-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0016_auto_20180409_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listicle',
            name='image',
            field=models.FileField(upload_to='tips/listicle/images/%Y/%m/%d'),
        ),
    ]
