# Generated by Django 2.0.3 on 2018-03-22 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0017_category_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
    ]
