# Generated by Django 2.0.3 on 2018-04-09 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0017_auto_20180409_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listicle',
            name='articles',
            field=models.ManyToManyField(limit_choices_to={'articles': models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tips.Category')}, related_name='listicle_articles', to='tips.Article'),
        ),
    ]
