# Generated by Django 2.0.3 on 2018-04-13 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0017_auto_20180413_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent_writer',
            new_name='parent_author',
        ),
    ]
