# Generated by Django 2.0.3 on 2018-03-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0018_remove_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=20, null=True, verbose_name='Title'),
        ),
    ]
