# Generated by Django 2.0.3 on 2018-04-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0018_auto_20180409_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listicle',
            name='articles',
            field=models.ManyToManyField(limit_choices_to={'is_active': True}, related_name='listicle_articles', to='tips.Article'),
        ),
    ]
