# Generated by Django 2.0.3 on 2018-04-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0018_auto_20180413_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['group', 'id', 'parent_author']},
        ),
    ]
