# Generated by Django 2.0.3 on 2018-03-22 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0019_category_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
