# Generated by Django 2.0.3 on 2018-04-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0019_auto_20180413_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='seq_in_group',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
