# Generated by Django 2.0.3 on 2018-03-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0021_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=20, null=True, verbose_name='Category'),
        ),
    ]
