# Generated by Django 2.0.3 on 2018-03-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0022_auto_20180322_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(default='test', max_length=20, verbose_name='Category'),
            preserve_default=False,
        ),
    ]
