# Generated by Django 2.0.3 on 2018-03-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0023_auto_20180322_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default='test1', max_length=100),
            preserve_default=False,
        ),
    ]
