# Generated by Django 2.0.3 on 2018-05-02 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0023_auto_20180502_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(allow_unicode=True, editable=False, max_length=100),
        ),
    ]
