# Generated by Django 2.0.3 on 2018-05-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0024_auto_20180502_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.FileField(default='', upload_to='tips/category/images/'),
            preserve_default=False,
        ),
    ]
