# Generated by Django 2.0.3 on 2018-03-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0025_auto_20180322_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to='tips/images/', verbose_name='File'),
        ),
    ]
