# Generated by Django 2.0.3 on 2018-06-05 00:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0027_auto_20180517_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
