# Generated by Django 2.0.3 on 2018-03-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0027_auto_20180322_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
