# Generated by Django 2.0.1 on 2018-03-22 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0028_auto_20180322_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
