# Generated by Django 2.0.3 on 2018-06-25 01:10

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0033_auto_20180619_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listicle',
            name='articles',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='listicle_articles', to='tips.Article'),
        ),
    ]
