# Generated by Django 2.0.3 on 2018-06-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0034_auto_20180625_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listicle',
            name='articles',
            field=models.ManyToManyField(related_name='listicle_articles', to='tips.Article'),
        ),
    ]
