# Generated by Django 2.0.7 on 2018-07-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0037_article_find_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
