# Generated by Django 2.0.3 on 2018-04-26 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_articles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='articles',
            new_name='article_cart',
        ),
    ]
