# Generated by Django 2.0.3 on 2018-05-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180426_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='article_cart',
            field=models.ManyToManyField(blank=True, related_name='user_articles', to='tips.Article'),
        ),
    ]
