# Generated by Django 2.0.3 on 2018-05-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180516_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subscription',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
