# Generated by Django 2.0.3 on 2018-06-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0032_auto_20180605_0957'),
        ('accounts', '0011_remove_userprofile_recommendation_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='article_cart',
            field=models.ManyToManyField(blank=True, related_name='user_articles', to='tips.Article'),
        ),
    ]
