# Generated by Django 2.0.1 on 2018-02-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapaddress',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mapaddress',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
