# Generated by Django 2.0.3 on 2018-06-18 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0032_auto_20180605_0957'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recommendtion',
            new_name='Recommendation',
        ),
        migrations.AddField(
            model_name='image',
            name='recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recommendation.Recommendation'),
        ),
    ]
