# Generated by Django 2.0.3 on 2018-06-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_auto_20180618_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='phone_num',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
