# Generated by Django 2.0.3 on 2018-06-18 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommendation', '0003_auto_20180618_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.PositiveIntegerField(default=None, null=True)),
                ('parent_author', models.CharField(default=None, max_length=100, null=True)),
                ('group', models.PositiveIntegerField(default=None)),
                ('seq_in_group', models.PositiveIntegerField(default=0)),
                ('depth', models.PositiveIntegerField(default=1)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recom_comment_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['group', 'seq_in_group'],
            },
        ),
        migrations.AddField(
            model_name='recommendation',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.Recommendation'),
        ),
    ]
