# Generated by Django 2.0.3 on 2018-06-19 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0004_auto_20180618_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='recommendation.Recommendation'),
        ),
    ]
