# Generated by Django 2.0.3 on 2018-06-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0005_auto_20180619_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', editable=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='video',
            field=models.FileField(blank=True, upload_to='recommendation/video/%Y/%m/%d'),
        ),
    ]
