# Generated by Django 2.0.3 on 2018-07-12 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0006_auto_20180621_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='text',
            new_name='about',
        ),
    ]
