# Generated by Django 2.0.7 on 2018-07-19 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='q_title',
            new_name='b_title',
        ),
    ]
